--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: destinations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.destinations (
    id integer NOT NULL,
    city character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    clues text[] NOT NULL,
    fun_facts text[] NOT NULL,
    trivia text[] NOT NULL,
    options text[] NOT NULL,
    correct_answer character varying(100) NOT NULL
);


ALTER TABLE public.destinations OWNER TO postgres;

--
-- Name: destinations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.destinations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.destinations_id_seq OWNER TO postgres;

--
-- Name: destinations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.destinations_id_seq OWNED BY public.destinations.id;


--
-- Name: destinations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.destinations ALTER COLUMN id SET DEFAULT nextval('public.destinations_id_seq'::regclass);


--
-- Data for Name: destinations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.destinations (id, city, country, clues, fun_facts, trivia, options, correct_answer) FROM stdin;
1	Paris	France	{"This city is home to a famous tower that sparkles every night.","Known as the \\"City of Love\\" and a hub for fashion and art."}	{"The Eiffel Tower was supposed to be dismantled after 20 years but was saved because it was useful for radio transmissions!","Paris has only one stop sign in the entire city-most intersections rely on priority-to-the-right rules."}	{"This city is famous for its croissants and macarons.Bon appetit!","Paris was originally a Roman city called Lutetia."}	{Paris,London,Rome,Berlin}	Paris
2	Paris	France	{"This city is home to a famous tower that sparkles every night.","Known as the \\"City of Love\\" and a hub for fashion and art."}	{"The Eiffel Tower was supposed to be dismantled after 20 years but was saved because it was useful for radio transmissions!","Paris has only one stop sign in the entire cityâ€”most intersections rely on priority-to-the-right rules."}	{"This city is famous for its croissants and macarons. Bon appÃ©tit!","Paris was originally a Roman city called Lutetia."}	{Paris,London,Rome,Berlin}	Paris
3	Tokyo	Japan	{"This city has the busiest pedestrian crossing in the world.","You can visit an entire district dedicated to anime, manga, and gaming."}	{"Tokyo was originally a small fishing village called Edo before becoming the bustling capital it is today!","More than 14 million people live in Tokyo, making it one of the most populous cities in the world."}	{"The city has over 160,000 restaurants, more than any other city in the world.","Tokyoâ€™s subway system is so efficient that train delays of just a few minutes come with formal apologies."}	{Tokyo,Seoul,Beijing,Bangkok}	Tokyo
4	New York	USA	{"Home to a green statue gifted by France in the 1800s.","Nicknamed \\"The Big Apple\\" and known for its Broadway theaters."}	{"The Statue of Liberty was originally a copper color before oxidizing to its iconic green patina.","Times Square was once called Longacre Square before being renamed in 1904."}	{"New York City has 468 subway stations, making it one of the most complex transit systems in the world.","The Empire State Building has its own zip code: 10118."}	{"New York","Los Angeles",Chicago,"San Francisco"}	New York
5	Paris	France	{"This city is home to a famous tower that sparkles every night.","Known as the \\"City of Love\\" and a hub for fashion and art."}	{"The Eiffel Tower was supposed to be dismantled after 20 years but was saved because it was useful for radio transmissions!","Paris has only one stop sign in the entire city--most intersections rely on priority-to-the-right rules."}	{"This city is famous for its croissants and macarons. Bon appetit!","Paris was originally a Roman city called Lutetia."}	{"Eiffel Tower","Notre-Dame Cathedral","Louvre Museum"}	Eiffel Tower
6	London	United Kingdom	{"Home to a giant clock tower that chimes every hour.","Famous for its double-decker buses and black taxis."}	{"Big Ben is actually the name of the bell inside the clock tower, not the tower itself!","London has over 170 museums, more than any other city in the world."}	{"London's underground is the oldest metro system in the world, dating back to 1863.","The Queen's guards at Buckingham Palace are trained not to react to tourists."}	{"Big Ben","London Eye","Tower of London"}	Big Ben
7	Rome	Italy	{"This city has an ancient amphitheater that once hosted gladiator battles.","Known for its world-famous pasta and gelato."}	{"The Colosseum was originally called the Flavian Amphitheater.","There's a secret keyhole in Rome that perfectly frames a view of St. Peter's Basilica."}	{"The Vatican City, inside Rome, is the smallest country in the world.","Rome has more fountains than any other city, with over 1,500!"}	{Colosseum,Pantheon,"Trevi Fountain"}	Colosseum
8	Tokyo	Japan	{"This city has the busiest pedestrian crossing in the world.","You can visit an entire district dedicated to anime, manga, and gaming."}	{"Tokyo was originally a small fishing village called Edo before becoming the bustling capital it is today!","More than 14 million people live in Tokyo, making it one of the most populous cities in the world."}	{"The city has over 160,000 restaurants, more than any other city in the world.","Tokyo's subway system is so efficient that train delays of just a few minutes come with formal apologies."}	{"Shibuya Crossing","Tokyo Tower","Meiji Shrine"}	Shibuya Crossing
9	Seoul	South Korea	{"This city is home to the world's most technologically advanced subway system.","Famous for K-pop, kimchi, and K-dramas."}	{"Seoul's Namdaemun Market has been around since 1414!","There are more than 13,000 convenience stores in Seoul alone."}	{"South Korea has a \\"love lock\\" tradition at N Seoul Tower.","Seoul's subway stations have book rental machines for passengers."}	{"Gyeongbokgung Palace","N Seoul Tower","Bukchon Hanok Village"}	Gyeongbokgung Palace
10	New York	USA	{"Home to a green statue gifted by France in the 1800s.","Nicknamed \\"The Big Apple\\" and known for its Broadway theaters."}	{"The Statue of Liberty was originally a copper color before oxidizing to its iconic green patina.","Times Square was once called Longacre Square before being renamed in 1904."}	{"New York City has 468 subway stations, making it one of the most complex transit systems in the world.","The Empire State Building has its own zip code: 10118."}	{"Statue of Liberty","Central Park","Empire State Building"}	Statue of Liberty
11	Rio de Janeiro	Brazil	{"This city has a massive statue of Jesus overlooking it from a mountain.","Known for its carnival celebrations and samba music."}	{"The Christ the Redeemer statue was built in France before being assembled in Brazil.","Rio's Copacabana beach gets its name from a Bolivian Virgin."}	{"The city's MaracanÃ£ stadium once held a record attendance of 199,854 for a football match.","Rio's Sugarloaf Mountain has a cable car that offers panoramic city views."}	{"Christ the Redeemer","Sugarloaf Mountain","MaracanÃ£ Stadium"}	Christ the Redeemer
39	Athens	Greece	{"Known for its ancient ruins and the Acropolis.","Birthplace of democracy."}	{"The Parthenon is a symbol of ancient Greek civilization.","Greek yogurt is a popular food."}	{"Ouzo is a traditional Greek drink.","The city has a rich history of philosophy and literature."}	{Acropolis,Parthenon,"Ancient Agora"}	Acropolis
12	Cairo	Egypt	{"This city has the last standing Wonder of the Ancient World.","It is home to a river that runs through 11 countries."}	{"The Great Pyramid of Giza was the tallest man-made structure for 3,800 years.","Cairo is known as \\"The City of a Thousand Minarets\\" due to its many mosques."}	{"The Sphinx originally had a nose, but it was destroyed in history.","The Nile River is the longest in the world, stretching over 6,600 km."}	{"Great Pyramid of Giza",Sphinx,"Cairo Museum"}	Great Pyramid of Giza
13	Sydney	Australia	{"This city has a white sail-shaped building famous for its performances.","It is home to one of the world's most beautiful harbors."}	{"The Sydney Opera House took 14 years to complete.","Sydney's Bondi Beach has some of the most dangerous riptides in the world."}	{"Sydney was founded as a British penal colony in 1788.","The Sydney Harbour Bridge is nicknamed \\"The Coathanger\\" because of its shape."}	{"Sydney Opera House","Sydney Harbour Bridge","Bondi Beach"}	Sydney Opera House
14	Dubai	UAE	{"This city has the tallest building in the world.","Known for its man-made islands shaped like a palm tree."}	{"Burj Khalifa is so tall that you can watch the sunset twice on the same day--from different floors!","Dubai has a police force that drives luxury sports cars."}	{"The city has an indoor ski resort despite being in the desert.","Dubai has a gold vending machine where you can buy gold bars!"}	{"Burj Khalifa","Palm Jumeirah","Dubai Mall"}	Burj Khalifa
15	Paris	France	{"This city is home to a famous tower that sparkles every night.","Known as the \\"City of Love\\" and a hub for fashion and art."}	{"The Eiffel Tower was supposed to be dismantled after 20 years but was saved because it was useful for radio transmissions!","Paris has only one stop sign in the entire city--most intersections rely on priority-to-the-right rules."}	{"This city is famous for its croissants and macarons. Bon appetit!","Paris was originally a Roman city called Lutetia."}	{"Eiffel Tower","Notre-Dame Cathedral","Louvre Museum"}	Eiffel Tower
16	London	United Kingdom	{"Home to a giant clock tower that chimes every hour.","Famous for its double-decker buses and black taxis."}	{"Big Ben is actually the name of the bell inside the clock tower, not the tower itself!","London has over 170 museums, more than any other city in the world."}	{"London's underground is the oldest metro system in the world, dating back to 1863.","The Queen's guards at Buckingham Palace are trained not to react to tourists."}	{"Big Ben","London Eye","Tower of London"}	Big Ben
17	Rome	Italy	{"This city has an ancient amphitheater that once hosted gladiator battles.","Known for its world-famous pasta and gelato."}	{"The Colosseum was originally called the Flavian Amphitheater.","There's a secret keyhole in Rome that perfectly frames a view of St. Peter's Basilica."}	{"The Vatican City, inside Rome, is the smallest country in the world.","Rome has more fountains than any other city, with over 1,500!"}	{Colosseum,Pantheon,"Trevi Fountain"}	Colosseum
18	Tokyo	Japan	{"This city has the busiest pedestrian crossing in the world.","You can visit an entire district dedicated to anime, manga, and gaming."}	{"Tokyo was originally a small fishing village called Edo before becoming the bustling capital it is today!","More than 14 million people live in Tokyo, making it one of the most populous cities in the world."}	{"The city has over 160,000 restaurants, more than any other city in the world.","Tokyo's subway system is so efficient that train delays of just a few minutes come with formal apologies."}	{"Shibuya Crossing","Tokyo Tower","Meiji Shrine"}	Shibuya Crossing
19	Seoul	South Korea	{"This city is home to the world's most technologically advanced subway system.","Famous for K-pop, kimchi, and K-dramas."}	{"Seoul's Namdaemun Market has been around since 1414!","There are more than 13,000 convenience stores in Seoul alone."}	{"South Korea has a \\"love lock\\" tradition at N Seoul Tower.","Seoul's subway stations have book rental machines for passengers."}	{"Gyeongbokgung Palace","N Seoul Tower","Bukchon Hanok Village"}	Gyeongbokgung Palace
20	New York	USA	{"Home to a green statue gifted by France in the 1800s.","Nicknamed \\"The Big Apple\\" and known for its Broadway theaters."}	{"The Statue of Liberty was originally a copper color before oxidizing to its iconic green patina.","Times Square was once called Longacre Square before being renamed in 1904."}	{"New York City has 468 subway stations, making it one of the most complex transit systems in the world.","The Empire State Building has its own zip code: 10118."}	{"Statue of Liberty","Central Park","Empire State Building"}	Statue of Liberty
21	Rio de Janeiro	Brazil	{"This city has a massive statue of Jesus overlooking it from a mountain.","Known for its carnival celebrations and samba music."}	{"The Christ the Redeemer statue was built in France before being assembled in Brazil.","Rio's Copacabana beach gets its name from a Bolivian Virgin."}	{"The city's MaracanÃ£ stadium once held a record attendance of 199,854 for a football match.","Rio's Sugarloaf Mountain has a cable car that offers panoramic city views."}	{"Christ the Redeemer","Sugarloaf Mountain","MaracanÃ£ Stadium"}	Christ the Redeemer
22	Cairo	Egypt	{"This city has the last standing Wonder of the Ancient World.","It is home to a river that runs through 11 countries."}	{"The Great Pyramid of Giza was the tallest man-made structure for 3,800 years.","Cairo is known as \\"The City of a Thousand Minarets\\" due to its many mosques."}	{"The Sphinx originally had a nose, but it was destroyed in history.","The Nile River is the longest in the world, stretching over 6,600 km."}	{"Great Pyramid of Giza",Sphinx,"Cairo Museum"}	Great Pyramid of Giza
23	Sydney	Australia	{"This city has a white sail-shaped building famous for its performances.","It is home to one of the world's most beautiful harbors."}	{"The Sydney Opera House took 14 years to complete.","Sydney's Bondi Beach has some of the most dangerous riptides in the world."}	{"Sydney was founded as a British penal colony in 1788.","The Sydney Harbour Bridge is nicknamed \\"The Coathanger\\" because of its shape."}	{"Sydney Opera House","Sydney Harbour Bridge","Bondi Beach"}	Sydney Opera House
24	Dubai	UAE	{"This city has the tallest building in the world.","Known for its man-made islands shaped like a palm tree."}	{"Burj Khalifa is so tall that you can watch the sunset twice on the same day--from different floors!","Dubai has a police force that drives luxury sports cars."}	{"The city has an indoor ski resort despite being in the desert.","Dubai has a gold vending machine where you can buy gold bars!"}	{"Burj Khalifa","Palm Jumeirah","Dubai Mall"}	Burj Khalifa
25	Berlin	Germany	{"Known for its historical landmarks and vibrant arts scene.","Divided during the Cold War."}	{"The Berlin Wall fell in 1989.","Berlin has more bridges than Venice."}	{"The Brandenburg Gate is a symbol of German reunification.","Currywurst is a popular street food."}	{"Brandenburg Gate","Berlin Wall Memorial","Reichstag Building"}	Brandenburg Gate
26	Vienna	Austria	{"Known for its classical music and imperial palaces.","Home to the Habsburg dynasty."}	{"Vienna is known as the \\"City of Music.\\"","The SchÃ¶nbrunn Palace was the summer residence of the Habsburgs."}	{"Sacher torte is a famous Viennese dessert.","Vienna has a rich coffeehouse culture."}	{"SchÃ¶nbrunn Palace","St. Stephen's Cathedral","Belvedere Palace"}	SchÃ¶nbrunn Palace
27	Prague	Czech Republic	{"Known for its medieval architecture and Charles Bridge.","Home to Prague Castle."}	{"Prague Castle is one of the largest ancient castles in the world.","The Astronomical Clock is a popular tourist attraction."}	{"Czech beer is world-renowned.","The city has a rich history of art and literature."}	{"Prague Castle","Charles Bridge","Old Town Square"}	Prague Castle
28	Budapest	Hungary	{"Known for its thermal baths and Danube River views.","Divided by the Danube into Buda and Pest."}	{"Budapest has numerous thermal baths.","The Hungarian Parliament Building is a stunning example of Gothic Revival architecture."}	{"Goulash is a traditional Hungarian dish.","The city has a vibrant nightlife."}	{"Hungarian Parliament Building","SzÃ©chenyi Thermal Bath","Chain Bridge"}	Hungarian Parliament Building
29	Lisbon	Portugal	{"Known for its historic neighborhoods and trams.","Home to the BelÃ©m Tower."}	{"Lisbon is one of the oldest cities in Western Europe.","Pastel de nata is a famous Portuguese pastry."}	{"The city has seven hills.","Fado music is a traditional Portuguese genre."}	{"BelÃ©m Tower","JerÃ³nimos Monastery","SÃ£o Jorge Castle"}	BelÃ©m Tower
30	Copenhagen	Denmark	{"Known for its colorful harbor and Little Mermaid statue.","Home to Tivoli Gardens."}	{"Copenhagen is a bicycle-friendly city.","Nyhavn is a popular harbor district."}	{"Danish design is world-renowned.","SmÃ¸rrebrÃ¸d is a traditional Danish open-faced sandwich."}	{"The Little Mermaid","Tivoli Gardens",Nyhavn}	The Little Mermaid
31	Stockholm	Sweden	{"Known for its archipelago and Nobel Prize ceremonies.","Built on 14 islands."}	{"Stockholm is known as the \\"Venice of the North.\\"","The Vasa Museum houses a 17th-century warship."}	{"Swedish meatballs are a popular dish.","The city has a rich history of design and innovation."}	{"Vasa Museum","Gamla Stan","Royal Palace"}	Vasa Museum
32	Helsinki	Finland	{"Known for its design district and saunas.","Home to Suomenlinna sea fortress."}	{"Helsinki is known as the \\"Daughter of the Baltic.\\"","Finnish saunas are a cultural tradition."}	{"Reindeer meat is a traditional Finnish food.","The city has a vibrant arts scene."}	{Suomenlinna,"Helsinki Cathedral","Market Square"}	Suomenlinna
33	Dublin	Ireland	{"Known for its lively pubs and Guinness brewery.","Home to Trinity College."}	{"Dublin is known for its friendly atmosphere.","The Book of Kells is housed in Trinity College."}	{"Irish stew is a traditional dish.","The city has a rich literary history."}	{"Trinity College","Guinness Storehouse","St. Patrick's Cathedral"}	Trinity College
34	Edinburgh	Scotland	{"Known for its medieval Old Town and Edinburgh Castle.","Home to the Fringe Festival."}	{"Edinburgh Castle sits atop an extinct volcano.","The Royal Mile connects Edinburgh Castle and Holyrood Palace."}	{"Haggis is a traditional Scottish dish.","The city has a rich history of literature and philosophy."}	{"Edinburgh Castle","Royal Mile","Arthur's Seat"}	Edinburgh Castle
35	Brussels	Belgium	{"Known for its Grand Place and chocolate.","Headquarters of the European Union."}	{"The Grand Place is a UNESCO World Heritage Site.","Belgian waffles are a popular treat."}	{"Belgian beer is world-renowned.","Manneken Pis is a famous landmark."}	{"Grand Place",Atomium,"Manneken Pis"}	Grand Place
36	Zurich	Switzerland	{"Known for its banking industry and Lake Zurich.","Home to the Swiss National Museum."}	{"Zurich is known for its high quality of life.","The Bahnhofstrasse is a famous shopping street."}	{"Swiss chocolate and cheese are world-renowned.","The city has a rich history of art and design."}	{"Lake Zurich",Bahnhofstrasse,"Swiss National Museum"}	Lake Zurich
37	Oslo	Norway	{"Known for its fjords and Viking history.","Home to the Viking Ship Museum."}	{"Oslo is surrounded by forests and fjords.","The Vigeland Sculpture Park is a popular tourist attraction."}	{"Salmon is a staple of Norwegian cuisine.","The city has a rich history of exploration."}	{"Viking Ship Museum","Vigeland Sculpture Park","Oslo Opera House"}	Viking Ship Museum
38	Reykjavik	Iceland	{"Known for its geothermal pools and Northern Lights.","Home to HallgrÃ­mskirkja church."}	{"Reykjavik is the northernmost capital city in the world.","The Blue Lagoon is a popular geothermal spa."}	{"Lamb is a staple of Icelandic cuisine.","The city has a vibrant arts and music scene."}	{HallgrÃ­mskirkja,"Blue Lagoon","Harpa Concert Hall"}	HallgrÃ­mskirkja
40	Istanbul	Turkey	{"Known for its historical landmarks and Bosphorus Strait.","Straddles two continents."}	{"The Hagia Sophia was originally a church, then a mosque, and now a museum.","Turkish delight is a popular sweet."}	{"Turkish coffee is a traditional drink.","The city has a rich history of empires."}	{"Hagia Sophia","Blue Mosque","Topkapi Palace"}	Hagia Sophia
41	Jerusalem	Israel	{"Known for its religious significance to Judaism, Christianity, and Islam.","Home to the Western Wall."}	{"The Old City of Jerusalem is a UNESCO World Heritage Site.","Hummus is a popular food."}	{"Falafel is a traditional Middle Eastern dish.","The city has a rich history of conflict and coexistence."}	{"Western Wall","Dome of the Rock","Church of the Holy Sepulchre"}	Western Wall
42	Mecca	Saudi Arabia	{"The holiest city in Islam.","Home to the Kaaba."}	{"Millions of Muslims make the Hajj pilgrimage to Mecca each year.","Dates are a popular food."}	{"Arabic coffee is a traditional drink.","The city has a rich history of Islamic tradition."}	{Kaaba,"Masjid al-Haram","Mount Arafat"}	Kaaba
43	Paris	France	{"This city is home to a famous tower that sparkles every night.","Known as the \\"City of Love\\" and a hub for fashion and art."}	{"The Eiffel Tower was supposed to be dismantled after 20 years but was saved because it was useful for radio transmissions!","Paris has only one stop sign in the entire city--most intersections rely on priority-to-the-right rules."}	{"This city is famous for its croissants and macarons. Bon appetit!","Paris was originally a Roman city called Lutetia."}	{"Eiffel Tower","Notre-Dame Cathedral","Louvre Museum"}	Eiffel Tower
44	London	United Kingdom	{"Home to a giant clock tower that chimes every hour.","Famous for its double-decker buses and black taxis."}	{"Big Ben is actually the name of the bell inside the clock tower, not the tower itself!","London has over 170 museums, more than any other city in the world."}	{"London's underground is the oldest metro system in the world, dating back to 1863.","The Queen's guards at Buckingham Palace are trained not to react to tourists."}	{"Big Ben","London Eye","Tower of London"}	Big Ben
45	Rome	Italy	{"This city has an ancient amphitheater that once hosted gladiator battles.","Known for its world-famous pasta and gelato."}	{"The Colosseum was originally called the Flavian Amphitheater.","There's a secret keyhole in Rome that perfectly frames a view of St. Peter's Basilica."}	{"The Vatican City, inside Rome, is the smallest country in the world.","Rome has more fountains than any other city, with over 1,500!"}	{Colosseum,Pantheon,"Trevi Fountain"}	Colosseum
46	Tokyo	Japan	{"This city has the busiest pedestrian crossing in the world.","You can visit an entire district dedicated to anime, manga, and gaming."}	{"Tokyo was originally a small fishing village called Edo before becoming the bustling capital it is today!","More than 14 million people live in Tokyo, making it one of the most populous cities in the world."}	{"The city has over 160,000 restaurants, more than any other city in the world.","Tokyo's subway system is so efficient that train delays of just a few minutes come with formal apologies."}	{"Shibuya Crossing","Tokyo Tower","Meiji Shrine"}	Shibuya Crossing
47	Seoul	South Korea	{"This city is home to the world's most technologically advanced subway system.","Famous for K-pop, kimchi, and K-dramas."}	{"Seoul's Namdaemun Market has been around since 1414!","There are more than 13,000 convenience stores in Seoul alone."}	{"South Korea has a \\"love lock\\" tradition at N Seoul Tower.","Seoul's subway stations have book rental machines for passengers."}	{"Gyeongbokgung Palace","N Seoul Tower","Bukchon Hanok Village"}	Gyeongbokgung Palace
48	New York	USA	{"Home to a green statue gifted by France in the 1800s.","Nicknamed \\"The Big Apple\\" and known for its Broadway theaters."}	{"The Statue of Liberty was originally a copper color before oxidizing to its iconic green patina.","Times Square was once called Longacre Square before being renamed in 1904."}	{"New York City has 468 subway stations, making it one of the most complex transit systems in the world.","The Empire State Building has its own zip code: 10118."}	{"Statue of Liberty","Central Park","Empire State Building"}	Statue of Liberty
49	Rio de Janeiro	Brazil	{"This city has a massive statue of Jesus overlooking it from a mountain.","Known for its carnival celebrations and samba music."}	{"The Christ the Redeemer statue was built in France before being assembled in Brazil.","Rio's Copacabana beach gets its name from a Bolivian Virgin."}	{"The city's MaracanÃ£ stadium once held a record attendance of 199,854 for a football match.","Rio's Sugarloaf Mountain has a cable car that offers panoramic city views."}	{"Christ the Redeemer","Sugarloaf Mountain","MaracanÃ£ Stadium"}	Christ the Redeemer
50	Cairo	Egypt	{"This city has the last standing Wonder of the Ancient World.","It is home to a river that runs through 11 countries."}	{"The Great Pyramid of Giza was the tallest man-made structure for 3,800 years.","Cairo is known as \\"The City of a Thousand Minarets\\" due to its many mosques."}	{"The Sphinx originally had a nose, but it was destroyed in history.","The Nile River is the longest in the world, stretching over 6,600 km."}	{"Great Pyramid of Giza",Sphinx,"Cairo Museum"}	Great Pyramid of Giza
51	Sydney	Australia	{"This city has a white sail-shaped building famous for its performances.","It is home to one of the world's most beautiful harbors."}	{"The Sydney Opera House took 14 years to complete.","Sydney's Bondi Beach has some of the most dangerous riptides in the world."}	{"Sydney was founded as a British penal colony in 1788.","The Sydney Harbour Bridge is nicknamed \\"The Coathanger\\" because of its shape."}	{"Sydney Opera House","Sydney Harbour Bridge","Bondi Beach"}	Sydney Opera House
67	Athens	Greece	{"Known for its ancient ruins and the Acropolis.","Birthplace of democracy."}	{"The Parthenon is a symbol of ancient Greek civilization.","Greek yogurt is a popular food."}	{"Ouzo is a traditional Greek drink.","The city has a rich history of philosophy and literature."}	{Acropolis,Parthenon,"Ancient Agora"}	Acropolis
52	Dubai	UAE	{"This city has the tallest building in the world.","Known for its man-made islands shaped like a palm tree."}	{"Burj Khalifa is so tall that you can watch the sunset twice on the same day--from different floors!","Dubai has a police force that drives luxury sports cars."}	{"The city has an indoor ski resort despite being in the desert.","Dubai has a gold vending machine where you can buy gold bars!"}	{"Burj Khalifa","Palm Jumeirah","Dubai Mall"}	Burj Khalifa
53	Berlin	Germany	{"Known for its historical landmarks and vibrant arts scene.","Divided during the Cold War."}	{"The Berlin Wall fell in 1989.","Berlin has more bridges than Venice."}	{"The Brandenburg Gate is a symbol of German reunification.","Currywurst is a popular street food."}	{"Brandenburg Gate","Berlin Wall Memorial","Reichstag Building"}	Brandenburg Gate
54	Vienna	Austria	{"Known for its classical music and imperial palaces.","Home to the Habsburg dynasty."}	{"Vienna is known as the \\"City of Music.\\"","The SchÃ¶nbrunn Palace was the summer residence of the Habsburgs."}	{"Sacher torte is a famous Viennese dessert.","Vienna has a rich coffeehouse culture."}	{"SchÃ¶nbrunn Palace","St. Stephen's Cathedral","Belvedere Palace"}	SchÃ¶nbrunn Palace
55	Prague	Czech Republic	{"Known for its medieval architecture and Charles Bridge.","Home to Prague Castle."}	{"Prague Castle is one of the largest ancient castles in the world.","The Astronomical Clock is a popular tourist attraction."}	{"Czech beer is world-renowned.","The city has a rich history of art and literature."}	{"Prague Castle","Charles Bridge","Old Town Square"}	Prague Castle
56	Budapest	Hungary	{"Known for its thermal baths and Danube River views.","Divided by the Danube into Buda and Pest."}	{"Budapest has numerous thermal baths.","The Hungarian Parliament Building is a stunning example of Gothic Revival architecture."}	{"Goulash is a traditional Hungarian dish.","The city has a vibrant nightlife."}	{"Hungarian Parliament Building","SzÃ©chenyi Thermal Bath","Chain Bridge"}	Hungarian Parliament Building
57	Lisbon	Portugal	{"Known for its historic neighborhoods and trams.","Home to the BelÃ©m Tower."}	{"Lisbon is one of the oldest cities in Western Europe.","Pastel de nata is a famous Portuguese pastry."}	{"The city has seven hills.","Fado music is a traditional Portuguese genre."}	{"BelÃ©m Tower","JerÃ³nimos Monastery","SÃ£o Jorge Castle"}	BelÃ©m Tower
58	Copenhagen	Denmark	{"Known for its colorful harbor and Little Mermaid statue.","Home to Tivoli Gardens."}	{"Copenhagen is a bicycle-friendly city.","Nyhavn is a popular harbor district."}	{"Danish design is world-renowned.","SmÃ¸rrebrÃ¸d is a traditional Danish open-faced sandwich."}	{"The Little Mermaid","Tivoli Gardens",Nyhavn}	The Little Mermaid
59	Stockholm	Sweden	{"Known for its archipelago and Nobel Prize ceremonies.","Built on 14 islands."}	{"Stockholm is known as the \\"Venice of the North.\\"","The Vasa Museum houses a 17th-century warship."}	{"Swedish meatballs are a popular dish.","The city has a rich history of design and innovation."}	{"Vasa Museum","Gamla Stan","Royal Palace"}	Vasa Museum
60	Helsinki	Finland	{"Known for its design district and saunas.","Home to Suomenlinna sea fortress."}	{"Helsinki is known as the \\"Daughter of the Baltic.\\"","Finnish saunas are a cultural tradition."}	{"Reindeer meat is a traditional Finnish food.","The city has a vibrant arts scene."}	{Suomenlinna,"Helsinki Cathedral","Market Square"}	Suomenlinna
61	Dublin	Ireland	{"Known for its lively pubs and Guinness brewery.","Home to Trinity College."}	{"Dublin is known for its friendly atmosphere.","The Book of Kells is housed in Trinity College."}	{"Irish stew is a traditional dish.","The city has a rich literary history."}	{"Trinity College","Guinness Storehouse","St. Patrick's Cathedral"}	Trinity College
62	Edinburgh	Scotland	{"Known for its medieval Old Town and Edinburgh Castle.","Home to the Fringe Festival."}	{"Edinburgh Castle sits atop an extinct volcano.","The Royal Mile connects Edinburgh Castle and Holyrood Palace."}	{"Haggis is a traditional Scottish dish.","The city has a rich history of literature and philosophy."}	{"Edinburgh Castle","Royal Mile","Arthur's Seat"}	Edinburgh Castle
63	Brussels	Belgium	{"Known for its Grand Place and chocolate.","Headquarters of the European Union."}	{"The Grand Place is a UNESCO World Heritage Site.","Belgian waffles are a popular treat."}	{"Belgian beer is world-renowned.","Manneken Pis is a famous landmark."}	{"Grand Place",Atomium,"Manneken Pis"}	Grand Place
64	Zurich	Switzerland	{"Known for its banking industry and Lake Zurich.","Home to the Swiss National Museum."}	{"Zurich is known for its high quality of life.","The Bahnhofstrasse is a famous shopping street."}	{"Swiss chocolate and cheese are world-renowned.","The city has a rich history of art and design."}	{"Lake Zurich",Bahnhofstrasse,"Swiss National Museum"}	Lake Zurich
65	Oslo	Norway	{"Known for its fjords and Viking history.","Home to the Viking Ship Museum."}	{"Oslo is surrounded by forests and fjords.","The Vigeland Sculpture Park is a popular tourist attraction."}	{"Salmon is a staple of Norwegian cuisine.","The city has a rich history of exploration."}	{"Viking Ship Museum","Vigeland Sculpture Park","Oslo Opera House"}	Viking Ship Museum
66	Reykjavik	Iceland	{"Known for its geothermal pools and Northern Lights.","Home to HallgrÃ­mskirkja church."}	{"Reykjavik is the northernmost capital city in the world.","The Blue Lagoon is a popular geothermal spa."}	{"Lamb is a staple of Icelandic cuisine.","The city has a vibrant arts and music scene."}	{HallgrÃ­mskirkja,"Blue Lagoon","Harpa Concert Hall"}	HallgrÃ­mskirkja
68	Istanbul	Turkey	{"Known for its historical landmarks and Bosphorus Strait.","Straddles two continents."}	{"The Hagia Sophia was originally a church, then a mosque, and now a museum.","Turkish delight is a popular sweet."}	{"Turkish coffee is a traditional drink.","The city has a rich history of empires."}	{"Hagia Sophia","Blue Mosque","Topkapi Palace"}	Hagia Sophia
69	Jerusalem	Israel	{"Known for its religious significance to Judaism, Christianity, and Islam.","Home to the Western Wall."}	{"The Old City of Jerusalem is a UNESCO World Heritage Site.","Hummus is a popular food."}	{"Falafel is a traditional Middle Eastern dish.","The city has a rich history of conflict and coexistence."}	{"Western Wall","Dome of the Rock","Church of the Holy Sepulchre"}	Western Wall
70	Mecca	Saudi Arabia	{"The holiest city in Islam.","Home to the Kaaba."}	{"Millions of Muslims make the Hajj pilgrimage to Mecca each year.","Dates are a popular food."}	{"Arabic coffee is a traditional drink.","The city has a rich history of Islamic tradition."}	{Kaaba,"Masjid al-Haram","Mount Arafat"}	Kaaba
71	Amman	Jordan	{"Known for its ancient ruins and desert landscapes.","Gateway to Petra."}	{"Petra is a UNESCO World Heritage Site.","Jordanian hospitality is renowned."}	{"Mansaf is a traditional Jordanian dish.","The Dead Sea is a popular tourist destination."}	{Petra,"Wadi Rum",Citadel}	Petra
72	Muscat	Oman	{"Known for its stunning mosques and coastal beauty.","Rich in maritime history."}	{"The Sultan Qaboos Grand Mosque is a major landmark.","Omani frankincense is highly valued."}	{"Halwa is a traditional Omani sweet.","Omani daggers (khanjars) are a symbol of culture."}	{"Sultan Qaboos Grand Mosque","Royal Opera House Muscat","Mutrah Corniche"}	Sultan Qaboos Grand Mosque
73	Doha	Qatar	{"Known for its modern architecture and cultural institutions.","Rapidly developing city."}	{"The Museum of Islamic Art houses a world-class collection.","Doha is a major hub for international travel."}	{"Machboos is a traditional Qatari dish.","Qatar is known for its pearl diving history."}	{"Museum of Islamic Art","The Pearl-Qatar","Souq Waqif"}	Museum of Islamic Art
74	Kuwait City	Kuwait	{"Known for its modern skyline and cultural attractions.","Oil-rich nation."}	{"The Kuwait Towers are a symbol of the city.","Kuwait has a rich maritime heritage."}	{"Machboos is also popular in Kuwait.","Kuwait is known for its hospitality."}	{"Kuwait Towers","Grand Mosque","The Avenues Mall"}	Kuwait Towers
75	Abu Dhabi	UAE	{"The capital of the UAE.","Known for its impressive mosques and cultural sites."}	{"The Sheikh Zayed Grand Mosque is a stunning landmark.","Abu Dhabi is a major center for business and culture."}	{"Harees is a traditional Emirati dish.","Falconry is a traditional sport."}	{"Sheikh Zayed Grand Mosque","Louvre Abu Dhabi","Emirates Palace"}	Sheikh Zayed Grand Mosque
76	Paris	France	{"This city is home to a famous tower that sparkles every night.","Known as the \\"City of Love\\" and a hub for fashion and art."}	{"The Eiffel Tower was supposed to be dismantled after 20 years but was saved because it was useful for radio transmissions!","Paris has only one stop sign in the entire city--most intersections rely on priority-to-the-right rules."}	{"This city is famous for its croissants and macarons. Bon appetit!","Paris was originally a Roman city called Lutetia."}	{"Eiffel Tower","Notre-Dame Cathedral","Louvre Museum"}	Eiffel Tower
77	London	United Kingdom	{"Home to a giant clock tower that chimes every hour.","Famous for its double-decker buses and black taxis."}	{"Big Ben is actually the name of the bell inside the clock tower, not the tower itself!","London has over 170 museums, more than any other city in the world."}	{"London's underground is the oldest metro system in the world, dating back to 1863.","The Queen's guards at Buckingham Palace are trained not to react to tourists."}	{"Big Ben","London Eye","Tower of London"}	Big Ben
78	Rome	Italy	{"This city has an ancient amphitheater that once hosted gladiator battles.","Known for its world-famous pasta and gelato."}	{"The Colosseum was originally called the Flavian Amphitheater.","There's a secret keyhole in Rome that perfectly frames a view of St. Peter's Basilica."}	{"The Vatican City, inside Rome, is the smallest country in the world.","Rome has more fountains than any other city, with over 1,500!"}	{Colosseum,Pantheon,"Trevi Fountain"}	Colosseum
79	Tokyo	Japan	{"This city has the busiest pedestrian crossing in the world.","You can visit an entire district dedicated to anime, manga, and gaming."}	{"Tokyo was originally a small fishing village called Edo before becoming the bustling capital it is today!","More than 14 million people live in Tokyo, making it one of the most populous cities in the world."}	{"The city has over 160,000 restaurants, more than any other city in the world.","Tokyo's subway system is so efficient that train delays of just a few minutes come with formal apologies."}	{"Shibuya Crossing","Tokyo Tower","Meiji Shrine"}	Shibuya Crossing
80	Seoul	South Korea	{"This city is home to the world's most technologically advanced subway system.","Famous for K-pop, kimchi, and K-dramas."}	{"Seoul's Namdaemun Market has been around since 1414!","There are more than 13,000 convenience stores in Seoul alone."}	{"South Korea has a \\"love lock\\" tradition at N Seoul Tower.","Seoul's subway stations have book rental machines for passengers."}	{"Gyeongbokgung Palace","N Seoul Tower","Bukchon Hanok Village"}	Gyeongbokgung Palace
81	New York	USA	{"Home to a green statue gifted by France in the 1800s.","Nicknamed \\"The Big Apple\\" and known for its Broadway theaters."}	{"The Statue of Liberty was originally a copper color before oxidizing to its iconic green patina.","Times Square was once called Longacre Square before being renamed in 1904."}	{"New York City has 468 subway stations, making it one of the most complex transit systems in the world.","The Empire State Building has its own zip code: 10118."}	{"Statue of Liberty","Central Park","Empire State Building"}	Statue of Liberty
82	Rio de Janeiro	Brazil	{"This city has a massive statue of Jesus overlooking it from a mountain.","Known for its carnival celebrations and samba music."}	{"The Christ the Redeemer statue was built in France before being assembled in Brazil.","Rio's Copacabana beach gets its name from a Bolivian Virgin."}	{"The city's MaracanÃ£ stadium once held a record attendance of 199,854 for a football match.","Rio's Sugarloaf Mountain has a cable car that offers panoramic city views."}	{"Christ the Redeemer","Sugarloaf Mountain","MaracanÃ£ Stadium"}	Christ the Redeemer
83	Cairo	Egypt	{"This city has the last standing Wonder of the Ancient World.","It is home to a river that runs through 11 countries."}	{"The Great Pyramid of Giza was the tallest man-made structure for 3,800 years.","Cairo is known as \\"The City of a Thousand Minarets\\" due to its many mosques."}	{"The Sphinx originally had a nose, but it was destroyed in history.","The Nile River is the longest in the world, stretching over 6,600 km."}	{"Great Pyramid of Giza",Sphinx,"Cairo Museum"}	Great Pyramid of Giza
84	Sydney	Australia	{"This city has a white sail-shaped building famous for its performances.","It is home to one of the world's most beautiful harbors."}	{"The Sydney Opera House took 14 years to complete.","Sydney's Bondi Beach has some of the most dangerous riptides in the world."}	{"Sydney was founded as a British penal colony in 1788.","The Sydney Harbour Bridge is nicknamed \\"The Coathanger\\" because of its shape."}	{"Sydney Opera House","Sydney Harbour Bridge","Bondi Beach"}	Sydney Opera House
85	Dubai	UAE	{"This city has the tallest building in the world.","Known for its man-made islands shaped like a palm tree."}	{"Burj Khalifa is so tall that you can watch the sunset twice on the same day--from different floors!","Dubai has a police force that drives luxury sports cars."}	{"The city has an indoor ski resort despite being in the desert.","Dubai has a gold vending machine where you can buy gold bars!"}	{"Burj Khalifa","Palm Jumeirah","Dubai Mall"}	Burj Khalifa
86	Berlin	Germany	{"Known for its historical landmarks and vibrant arts scene.","Divided during the Cold War."}	{"The Berlin Wall fell in 1989.","Berlin has more bridges than Venice."}	{"The Brandenburg Gate is a symbol of German reunification.","Currywurst is a popular street food."}	{"Brandenburg Gate","Berlin Wall Memorial","Reichstag Building"}	Brandenburg Gate
87	Vienna	Austria	{"Known for its classical music and imperial palaces.","Home to the Habsburg dynasty."}	{"Vienna is known as the \\"City of Music.\\"","The SchÃ¶nbrunn Palace was the summer residence of the Habsburgs."}	{"Sacher torte is a famous Viennese dessert.","Vienna has a rich coffeehouse culture."}	{"SchÃ¶nbrunn Palace","St. Stephen's Cathedral","Belvedere Palace"}	SchÃ¶nbrunn Palace
88	Prague	Czech Republic	{"Known for its medieval architecture and Charles Bridge.","Home to Prague Castle."}	{"Prague Castle is one of the largest ancient castles in the world.","The Astronomical Clock is a popular tourist attraction."}	{"Czech beer is world-renowned.","The city has a rich history of art and literature."}	{"Prague Castle","Charles Bridge","Old Town Square"}	Prague Castle
89	Budapest	Hungary	{"Known for its thermal baths and Danube River views.","Divided by the Danube into Buda and Pest."}	{"Budapest has numerous thermal baths.","The Hungarian Parliament Building is a stunning example of Gothic Revival architecture."}	{"Goulash is a traditional Hungarian dish.","The city has a vibrant nightlife."}	{"Hungarian Parliament Building","SzÃ©chenyi Thermal Bath","Chain Bridge"}	Hungarian Parliament Building
90	Lisbon	Portugal	{"Known for its historic neighborhoods and trams.","Home to the BelÃ©m Tower."}	{"Lisbon is one of the oldest cities in Western Europe.","Pastel de nata is a famous Portuguese pastry."}	{"The city has seven hills.","Fado music is a traditional Portuguese genre."}	{"BelÃ©m Tower","JerÃ³nimos Monastery","SÃ£o Jorge Castle"}	BelÃ©m Tower
91	Copenhagen	Denmark	{"Known for its colorful harbor and Little Mermaid statue.","Home to Tivoli Gardens."}	{"Copenhagen is a bicycle-friendly city.","Nyhavn is a popular harbor district."}	{"Danish design is world-renowned.","SmÃ¸rrebrÃ¸d is a traditional Danish open-faced sandwich."}	{"The Little Mermaid","Tivoli Gardens",Nyhavn}	The Little Mermaid
92	Stockholm	Sweden	{"Known for its archipelago and Nobel Prize ceremonies.","Built on 14 islands."}	{"Stockholm is known as the \\"Venice of the North.\\"","The Vasa Museum houses a 17th-century warship."}	{"Swedish meatballs are a popular dish.","The city has a rich history of design and innovation."}	{"Vasa Museum","Gamla Stan","Royal Palace"}	Vasa Museum
93	Helsinki	Finland	{"Known for its design district and saunas.","Home to Suomenlinna sea fortress."}	{"Helsinki is known as the \\"Daughter of the Baltic.\\"","Finnish saunas are a cultural tradition."}	{"Reindeer meat is a traditional Finnish food.","The city has a vibrant arts scene."}	{Suomenlinna,"Helsinki Cathedral","Market Square"}	Suomenlinna
94	Dublin	Ireland	{"Known for its lively pubs and Guinness brewery.","Home to Trinity College."}	{"Dublin is known for its friendly atmosphere.","The Book of Kells is housed in Trinity College."}	{"Irish stew is a traditional dish.","The city has a rich literary history."}	{"Trinity College","Guinness Storehouse","St. Patrick's Cathedral"}	Trinity College
95	Edinburgh	Scotland	{"Known for its medieval Old Town and Edinburgh Castle.","Home to the Fringe Festival."}	{"Edinburgh Castle sits atop an extinct volcano.","The Royal Mile connects Edinburgh Castle and Holyrood Palace."}	{"Haggis is a traditional Scottish dish.","The city has a rich history of literature and philosophy."}	{"Edinburgh Castle","Royal Mile","Arthur's Seat"}	Edinburgh Castle
96	Brussels	Belgium	{"Known for its Grand Place and chocolate.","Headquarters of the European Union."}	{"The Grand Place is a UNESCO World Heritage Site.","Belgian waffles are a popular treat."}	{"Belgian beer is world-renowned.","Manneken Pis is a famous landmark."}	{"Grand Place",Atomium,"Manneken Pis"}	Grand Place
97	Zurich	Switzerland	{"Known for its banking industry and Lake Zurich.","Home to the Swiss National Museum."}	{"Zurich is known for its high quality of life.","The Bahnhofstrasse is a famous shopping street."}	{"Swiss chocolate and cheese are world-renowned.","The city has a rich history of art and design."}	{"Lake Zurich",Bahnhofstrasse,"Swiss National Museum"}	Lake Zurich
98	Oslo	Norway	{"Known for its fjords and Viking history.","Home to the Viking Ship Museum."}	{"Oslo is surrounded by forests and fjords.","The Vigeland Sculpture Park is a popular tourist attraction."}	{"Salmon is a staple of Norwegian cuisine.","The city has a rich history of exploration."}	{"Viking Ship Museum","Vigeland Sculpture Park","Oslo Opera House"}	Viking Ship Museum
99	Reykjavik	Iceland	{"Known for its geothermal pools and Northern Lights.","Home to HallgrÃ­mskirkja church."}	{"Reykjavik is the northernmost capital city in the world.","The Blue Lagoon is a popular geothermal spa."}	{"Lamb is a staple of Icelandic cuisine.","The city has a vibrant arts and music scene."}	{HallgrÃ­mskirkja,"Blue Lagoon","Harpa Concert Hall"}	HallgrÃ­mskirkja
100	Athens	Greece	{"Known for its ancient ruins and the Acropolis.","Birthplace of democracy."}	{"The Parthenon is a symbol of ancient Greek civilization.","Greek yogurt is a popular food."}	{"Ouzo is a traditional Greek drink.","The city has a rich history of philosophy and literature."}	{Acropolis,Parthenon,"Ancient Agora"}	Acropolis
101	Istanbul	Turkey	{"Known for its historical landmarks and Bosphorus Strait.","Straddles two continents."}	{"The Hagia Sophia was originally a church, then a mosque, and now a museum.","Turkish delight is a popular sweet."}	{"Turkish coffee is a traditional drink.","The city has a rich history of empires."}	{"Hagia Sophia","Blue Mosque","Topkapi Palace"}	Hagia Sophia
102	Jerusalem	Israel	{"Known for its religious significance to Judaism, Christianity, and Islam.","Home to the Western Wall."}	{"The Old City of Jerusalem is a UNESCO World Heritage Site.","Hummus is a popular food."}	{"Falafel is a traditional Middle Eastern dish.","The city has a rich history of conflict and coexistence."}	{"Western Wall","Dome of the Rock","Church of the Holy Sepulchre"}	Western Wall
103	Mecca	Saudi Arabia	{"The holiest city in Islam.","Home to the Kaaba."}	{"Millions of Muslims make the Hajj pilgrimage to Mecca each year.","Dates are a popular food."}	{"Arabic coffee is a traditional drink.","The city has a rich history of Islamic tradition."}	{Kaaba,"Masjid al-Haram","Mount Arafat"}	Kaaba
104	Amman	Jordan	{"Known for its ancient ruins and desert landscapes.","Gateway to Petra."}	{"Petra is a UNESCO World Heritage Site.","Jordanian hospitality is renowned."}	{"Mansaf is a traditional Jordanian dish.","The Dead Sea is a popular tourist destination."}	{Petra,"Wadi Rum",Citadel}	Petra
105	Muscat	Oman	{"Known for its stunning mosques and coastal beauty.","Rich in maritime history."}	{"The Sultan Qaboos Grand Mosque is a major landmark.","Omani frankincense is highly valued."}	{"Halwa is a traditional Omani sweet.","Omani daggers (khanjars) are a symbol of culture."}	{"Sultan Qaboos Grand Mosque","Royal Opera House Muscat","Mutrah Corniche"}	Sultan Qaboos Grand Mosque
106	Doha	Qatar	{"Known for its modern architecture and cultural institutions.","Rapidly developing city."}	{"The Museum of Islamic Art houses a world-class collection.","Doha is a major hub for international travel."}	{"Machboos is a traditional Qatari dish.","Qatar is known for its pearl diving history."}	{"Museum of Islamic Art","The Pearl-Qatar","Souq Waqif"}	Museum of Islamic Art
107	Kuwait City	Kuwait	{"Known for its modern skyline and cultural attractions.","Oil-rich nation."}	{"The Kuwait Towers are a symbol of the city.","Kuwait has a rich maritime heritage."}	{"Machboos is also popular in Kuwait.","Kuwait is known for its hospitality."}	{"Kuwait Towers","Grand Mosque","The Avenues Mall"}	Kuwait Towers
108	Abu Dhabi	UAE	{"The capital of the UAE.","Known for its impressive mosques and cultural sites."}	{"The Sheikh Zayed Grand Mosque is a stunning landmark.","Abu Dhabi is a major center for business and culture."}	{"Harees is a traditional Emirati dish.","Falconry is a traditional sport."}	{"Sheikh Zayed Grand Mosque","Louvre Abu Dhabi","Emirates Palace"}	Sheikh Zayed Grand Mosque
109	Kathmandu	Nepal	{"Known for its ancient temples and Himalayan views.","Gateway to the Himalayas."}	{"The Pashupatinath Temple is a major Hindu pilgrimage site.","Mount Everest is visible from Kathmandu on clear days."}	{"Momos are a popular Nepalese snack.","Thangka paintings are a traditional art form."}	{"Pashupatinath Temple","Swayambhunath (Monkey Temple)","Boudhanath Stupa"}	Pashupatinath Temple
110	Hanoi	Vietnam	{"Known for its Old Quarter and French colonial architecture.","Capital of Vietnam."}	{"Hoan Kiem Lake is a central landmark.","Water puppetry is a traditional art form."}	{"Pho is a famous Vietnamese noodle soup.","Vietnamese coffee is strong and flavorful."}	{"Hoan Kiem Lake","Old Quarter","Ho Chi Minh Mausoleum"}	Hoan Kiem Lake
111	MedellÃ­n	Colombia	{"Known for its innovative urban development and vibrant culture.","City of Eternal Spring."}	{"The MedellÃ­n Metro Cable offers stunning views of the city.","Fernando Botero's sculptures are a major attraction."}	{"Bandeja Paisa is a traditional Colombian dish.","MedellÃ­n is famous for its flower festival."}	{"Fernando Botero's Sculptures","MedellÃ­n Metro Cable","Plaza Botero"}	Fernando Botero's Sculptures
112	Quebec City	Canada	{"Known for its historic Old Town and French-Canadian culture.","Only walled city north of Mexico."}	{"The ChÃ¢teau Frontenac is a prominent landmark.","Quebec City is a UNESCO World Heritage Site."}	{"Poutine is a famous Canadian dish.","Maple syrup is a staple of Quebec cuisine."}	{"ChÃ¢teau Frontenac","Old Quebec","Plains of Abraham"}	ChÃ¢teau Frontenac
113	Auckland	New Zealand	{"Known for its harbors and Polynesian culture.","City of Sails."}	{"The Sky Tower offers panoramic views of the city.","Auckland is built on volcanic fields."}	{"Hangi is a traditional Maori cooking method.","New Zealand is famous for its adventure sports."}	{"Sky Tower","Auckland Harbour Bridge","Rangitoto Island"}	Sky Tower
114	Paris	France	{"This city is home to a famous tower that sparkles every night.","Known as the \\"City of Love\\" and a hub for fashion and art."}	{"The Eiffel Tower was supposed to be dismantled after 20 years but was saved because it was useful for radio transmissions!","Paris has only one stop sign in the entire city--most intersections rely on priority-to-the-right rules."}	{"This city is famous for its croissants and macarons. Bon appetit!","Paris was originally a Roman city called Lutetia."}	{"Eiffel Tower","Notre-Dame Cathedral","Louvre Museum"}	Eiffel Tower
115	London	United Kingdom	{"Home to a giant clock tower that chimes every hour.","Famous for its double-decker buses and black taxis."}	{"Big Ben is actually the name of the bell inside the clock tower, not the tower itself!","London has over 170 museums, more than any other city in the world."}	{"London's underground is the oldest metro system in the world, dating back to 1863.","The Queen's guards at Buckingham Palace are trained not to react to tourists."}	{"Big Ben","London Eye","Tower of London"}	Big Ben
116	Rome	Italy	{"This city has an ancient amphitheater that once hosted gladiator battles.","Known for its world-famous pasta and gelato."}	{"The Colosseum was originally called the Flavian Amphitheater.","There's a secret keyhole in Rome that perfectly frames a view of St. Peter's Basilica."}	{"The Vatican City, inside Rome, is the smallest country in the world.","Rome has more fountains than any other city, with over 1,500!"}	{Colosseum,Pantheon,"Trevi Fountain"}	Colosseum
117	Tokyo	Japan	{"This city has the busiest pedestrian crossing in the world.","You can visit an entire district dedicated to anime, manga, and gaming."}	{"Tokyo was originally a small fishing village called Edo before becoming the bustling capital it is today!","More than 14 million people live in Tokyo, making it one of the most populous cities in the world."}	{"The city has over 160,000 restaurants, more than any other city in the world.","Tokyo's subway system is so efficient that train delays of just a few minutes come with formal apologies."}	{"Shibuya Crossing","Tokyo Tower","Meiji Shrine"}	Shibuya Crossing
118	Seoul	South Korea	{"This city is home to the world's most technologically advanced subway system.","Famous for K-pop, kimchi, and K-dramas."}	{"Seoul's Namdaemun Market has been around since 1414!","There are more than 13,000 convenience stores in Seoul alone."}	{"South Korea has a \\"love lock\\" tradition at N Seoul Tower.","Seoul's subway stations have book rental machines for passengers."}	{"Gyeongbokgung Palace","N Seoul Tower","Bukchon Hanok Village"}	Gyeongbokgung Palace
119	New York	USA	{"Home to a green statue gifted by France in the 1800s.","Nicknamed \\"The Big Apple\\" and known for its Broadway theaters."}	{"The Statue of Liberty was originally a copper color before oxidizing to its iconic green patina.","Times Square was once called Longacre Square before being renamed in 1904."}	{"New York City has 468 subway stations, making it one of the most complex transit systems in the world.","The Empire State Building has its own zip code: 10118."}	{"Statue of Liberty","Central Park","Empire State Building"}	Statue of Liberty
120	Rio de Janeiro	Brazil	{"This city has a massive statue of Jesus overlooking it from a mountain.","Known for its carnival celebrations and samba music."}	{"The Christ the Redeemer statue was built in France before being assembled in Brazil.","Rio's Copacabana beach gets its name from a Bolivian Virgin."}	{"The city's MaracanÃ£ stadium once held a record attendance of 199,854 for a football match.","Rio's Sugarloaf Mountain has a cable car that offers panoramic city views."}	{"Christ the Redeemer","Sugarloaf Mountain","MaracanÃ£ Stadium"}	Christ the Redeemer
121	Cairo	Egypt	{"This city has the last standing Wonder of the Ancient World.","It is home to a river that runs through 11 countries."}	{"The Great Pyramid of Giza was the tallest man-made structure for 3,800 years.","Cairo is known as \\"The City of a Thousand Minarets\\" due to its many mosques."}	{"The Sphinx originally had a nose, but it was destroyed in history.","The Nile River is the longest in the world, stretching over 6,600 km."}	{"Great Pyramid of Giza",Sphinx,"Cairo Museum"}	Great Pyramid of Giza
122	Sydney	Australia	{"This city has a white sail-shaped building famous for its performances.","It is home to one of the world's most beautiful harbors."}	{"The Sydney Opera House took 14 years to complete.","Sydney's Bondi Beach has some of the most dangerous riptides in the world."}	{"Sydney was founded as a British penal colony in 1788.","The Sydney Harbour Bridge is nicknamed \\"The Coathanger\\" because of its shape."}	{"Sydney Opera House","Sydney Harbour Bridge","Bondi Beach"}	Sydney Opera House
123	Dubai	UAE	{"This city has the tallest building in the world.","Known for its man-made islands shaped like a palm tree."}	{"Burj Khalifa is so tall that you can watch the sunset twice on the same day--from different floors!","Dubai has a police force that drives luxury sports cars."}	{"The city has an indoor ski resort despite being in the desert.","Dubai has a gold vending machine where you can buy gold bars!"}	{"Burj Khalifa","Palm Jumeirah","Dubai Mall"}	Burj Khalifa
124	Berlin	Germany	{"Known for its historical landmarks and vibrant arts scene.","Divided during the Cold War."}	{"The Berlin Wall fell in 1989.","Berlin has more bridges than Venice."}	{"The Brandenburg Gate is a symbol of German reunification.","Currywurst is a popular street food."}	{"Brandenburg Gate","Berlin Wall Memorial","Reichstag Building"}	Brandenburg Gate
125	Vienna	Austria	{"Known for its classical music and imperial palaces.","Home to the Habsburg dynasty."}	{"Vienna is known as the \\"City of Music.\\"","The SchÃ¶nbrunn Palace was the summer residence of the Habsburgs."}	{"Sacher torte is a famous Viennese dessert.","Vienna has a rich coffeehouse culture."}	{"SchÃ¶nbrunn Palace","St. Stephen's Cathedral","Belvedere Palace"}	SchÃ¶nbrunn Palace
126	Prague	Czech Republic	{"Known for its medieval architecture and Charles Bridge.","Home to Prague Castle."}	{"Prague Castle is one of the largest ancient castles in the world.","The Astronomical Clock is a popular tourist attraction."}	{"Czech beer is world-renowned.","The city has a rich history of art and literature."}	{"Prague Castle","Charles Bridge","Old Town Square"}	Prague Castle
127	Budapest	Hungary	{"Known for its thermal baths and Danube River views.","Divided by the Danube into Buda and Pest."}	{"Budapest has numerous thermal baths.","The Hungarian Parliament Building is a stunning example of Gothic Revival architecture."}	{"Goulash is a traditional Hungarian dish.","The city has a vibrant nightlife."}	{"Hungarian Parliament Building","SzÃ©chenyi Thermal Bath","Chain Bridge"}	Hungarian Parliament Building
128	Lisbon	Portugal	{"Known for its historic neighborhoods and trams.","Home to the BelÃ©m Tower."}	{"Lisbon is one of the oldest cities in Western Europe.","Pastel de nata is a famous Portuguese pastry."}	{"The city has seven hills.","Fado music is a traditional Portuguese genre."}	{"BelÃ©m Tower","JerÃ³nimos Monastery","SÃ£o Jorge Castle"}	BelÃ©m Tower
129	Copenhagen	Denmark	{"Known for its colorful harbor and Little Mermaid statue.","Home to Tivoli Gardens."}	{"Copenhagen is a bicycle-friendly city.","Nyhavn is a popular harbor district."}	{"Danish design is world-renowned.","SmÃ¸rrebrÃ¸d is a traditional Danish open-faced sandwich."}	{"The Little Mermaid","Tivoli Gardens",Nyhavn}	The Little Mermaid
130	Stockholm	Sweden	{"Known for its archipelago and Nobel Prize ceremonies.","Built on 14 islands."}	{"Stockholm is known as the \\"Venice of the North.\\"","The Vasa Museum houses a 17th-century warship."}	{"Swedish meatballs are a popular dish.","The city has a rich history of design and innovation."}	{"Vasa Museum","Gamla Stan","Royal Palace"}	Vasa Museum
131	Helsinki	Finland	{"Known for its design district and saunas.","Home to Suomenlinna sea fortress."}	{"Helsinki is known as the \\"Daughter of the Baltic.\\"","Finnish saunas are a cultural tradition."}	{"Reindeer meat is a traditional Finnish food.","The city has a vibrant arts scene."}	{Suomenlinna,"Helsinki Cathedral","Market Square"}	Suomenlinna
132	Dublin	Ireland	{"Known for its lively pubs and Guinness brewery.","Home to Trinity College."}	{"Dublin is known for its friendly atmosphere.","The Book of Kells is housed in Trinity College."}	{"Irish stew is a traditional dish.","The city has a rich literary history."}	{"Trinity College","Guinness Storehouse","St. Patrick's Cathedral"}	Trinity College
133	Edinburgh	Scotland	{"Known for its medieval Old Town and Edinburgh Castle.","Home to the Fringe Festival."}	{"Edinburgh Castle sits atop an extinct volcano.","The Royal Mile connects Edinburgh Castle and Holyrood Palace."}	{"Haggis is a traditional Scottish dish.","The city has a rich history of literature and philosophy."}	{"Edinburgh Castle","Royal Mile","Arthur's Seat"}	Edinburgh Castle
134	Brussels	Belgium	{"Known for its Grand Place and chocolate.","Headquarters of the European Union."}	{"The Grand Place is a UNESCO World Heritage Site.","Belgian waffles are a popular treat."}	{"Belgian beer is world-renowned.","Manneken Pis is a famous landmark."}	{"Grand Place",Atomium,"Manneken Pis"}	Grand Place
135	Zurich	Switzerland	{"Known for its banking industry and Lake Zurich.","Home to the Swiss National Museum."}	{"Zurich is known for its high quality of life.","The Bahnhofstrasse is a famous shopping street."}	{"Swiss chocolate and cheese are world-renowned.","The city has a rich history of art and design."}	{"Lake Zurich",Bahnhofstrasse,"Swiss National Museum"}	Lake Zurich
136	Oslo	Norway	{"Known for its fjords and Viking history.","Home to the Viking Ship Museum."}	{"Oslo is surrounded by forests and fjords.","The Vigeland Sculpture Park is a popular tourist attraction."}	{"Salmon is a staple of Norwegian cuisine.","The city has a rich history of exploration."}	{"Viking Ship Museum","Vigeland Sculpture Park","Oslo Opera House"}	Viking Ship Museum
137	Reykjavik	Iceland	{"Known for its geothermal pools and Northern Lights.","Home to HallgrÃ­mskirkja church."}	{"Reykjavik is the northernmost capital city in the world.","The Blue Lagoon is a popular geothermal spa."}	{"Lamb is a staple of Icelandic cuisine.","The city has a vibrant arts and music scene."}	{HallgrÃ­mskirkja,"Blue Lagoon","Harpa Concert Hall"}	HallgrÃ­mskirkja
138	Athens	Greece	{"Known for its ancient ruins and the Acropolis.","Birthplace of democracy."}	{"The Parthenon is a symbol of ancient Greek civilization.","Greek yogurt is a popular food."}	{"Ouzo is a traditional Greek drink.","The city has a rich history of philosophy and literature."}	{Acropolis,Parthenon,"Ancient Agora"}	Acropolis
139	Istanbul	Turkey	{"Known for its historical landmarks and Bosphorus Strait.","Straddles two continents."}	{"The Hagia Sophia was originally a church, then a mosque, and now a museum.","Turkish delight is a popular sweet."}	{"Turkish coffee is a traditional drink.","The city has a rich history of empires."}	{"Hagia Sophia","Blue Mosque","Topkapi Palace"}	Hagia Sophia
140	Jerusalem	Israel	{"Known for its religious significance to Judaism, Christianity, and Islam.","Home to the Western Wall."}	{"The Old City of Jerusalem is a UNESCO World Heritage Site.","Hummus is a popular food."}	{"Falafel is a traditional Middle Eastern dish.","The city has a rich history of conflict and coexistence."}	{"Western Wall","Dome of the Rock","Church of the Holy Sepulchre"}	Western Wall
141	Mecca	Saudi Arabia	{"The holiest city in Islam.","Home to the Kaaba."}	{"Millions of Muslims make the Hajj pilgrimage to Mecca each year.","Dates are a popular food."}	{"Arabic coffee is a traditional drink.","The city has a rich history of Islamic tradition."}	{Kaaba,"Masjid al-Haram","Mount Arafat"}	Kaaba
142	Amman	Jordan	{"Known for its ancient ruins and desert landscapes.","Gateway to Petra."}	{"Petra is a UNESCO World Heritage Site.","Jordanian hospitality is renowned."}	{"Mansaf is a traditional Jordanian dish.","The Dead Sea is a popular tourist destination."}	{Petra,"Wadi Rum",Citadel}	Petra
143	Muscat	Oman	{"Known for its stunning mosques and coastal beauty.","Rich in maritime history."}	{"The Sultan Qaboos Grand Mosque is a major landmark.","Omani frankincense is highly valued."}	{"Halwa is a traditional Omani sweet.","Omani daggers (khanjars) are a symbol of culture."}	{"Sultan Qaboos Grand Mosque","Royal Opera House Muscat","Mutrah Corniche"}	Sultan Qaboos Grand Mosque
144	Doha	Qatar	{"Known for its modern architecture and cultural institutions.","Rapidly developing city."}	{"The Museum of Islamic Art houses a world-class collection.","Doha is a major hub for international travel."}	{"Machboos is a traditional Qatari dish.","Qatar is known for its pearl diving history."}	{"Museum of Islamic Art","The Pearl-Qatar","Souq Waqif"}	Museum of Islamic Art
145	Kuwait City	Kuwait	{"Known for its modern skyline and cultural attractions.","Oil-rich nation."}	{"The Kuwait Towers are a symbol of the city.","Kuwait has a rich maritime heritage."}	{"Machboos is also popular in Kuwait.","Kuwait is known for its hospitality."}	{"Kuwait Towers","Grand Mosque","The Avenues Mall"}	Kuwait Towers
146	Abu Dhabi	UAE	{"The capital of the UAE.","Known for its impressive mosques and cultural sites."}	{"The Sheikh Zayed Grand Mosque is a stunning landmark.","Abu Dhabi is a major center for business and culture."}	{"Harees is a traditional Emirati dish.","Falconry is a traditional sport."}	{"Sheikh Zayed Grand Mosque","Louvre Abu Dhabi","Emirates Palace"}	Sheikh Zayed Grand Mosque
147	Kathmandu	Nepal	{"Known for its ancient temples and Himalayan views.","Gateway to the Himalayas."}	{"The Pashupatinath Temple is a major Hindu pilgrimage site.","Mount Everest is visible from Kathmandu on clear days."}	{"Momos are a popular Nepalese snack.","Thangka paintings are a traditional art form."}	{"Pashupatinath Temple","Swayambhunath (Monkey Temple)","Boudhanath Stupa"}	Pashupatinath Temple
148	Hanoi	Vietnam	{"Known for its Old Quarter and French colonial architecture.","Capital of Vietnam."}	{"Hoan Kiem Lake is a central landmark.","Water puppetry is a traditional art form."}	{"Pho is a famous Vietnamese noodle soup.","Vietnamese coffee is strong and flavorful."}	{"Hoan Kiem Lake","Old Quarter","Ho Chi Minh Mausoleum"}	Hoan Kiem Lake
149	MedellÃ­n	Colombia	{"Known for its innovative urban development and vibrant culture.","City of Eternal Spring."}	{"The MedellÃ­n Metro Cable offers stunning views of the city.","Fernando Botero's sculptures are a major attraction."}	{"Bandeja Paisa is a traditional Colombian dish.","MedellÃ­n is famous for its flower festival."}	{"Fernando Botero's Sculptures","MedellÃ­n Metro Cable","Plaza Botero"}	Fernando Botero's Sculptures
150	Quebec City	Canada	{"Known for its historic Old Town and French-Canadian culture.","Only walled city north of Mexico."}	{"The ChÃ¢teau Frontenac is a prominent landmark.","Quebec City is a UNESCO World Heritage Site."}	{"Poutine is a famous Canadian dish.","Maple syrup is a staple of Quebec cuisine."}	{"ChÃ¢teau Frontenac","Old Quebec","Plains of Abraham"}	ChÃ¢teau Frontenac
151	Auckland	New Zealand	{"Known for its harbors and Polynesian culture.","City of Sails."}	{"The Sky Tower offers panoramic views of the city.","Auckland is built on volcanic fields."}	{"Hangi is a traditional Maori cooking method.","New Zealand is famous for its adventure sports."}	{"Sky Tower","Auckland Harbour Bridge","Rangitoto Island"}	Sky Tower
\.


--
-- Name: destinations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.destinations_id_seq', 151, true);


--
-- Name: destinations destinations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.destinations
    ADD CONSTRAINT destinations_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

