INSERT INTO destinations (city, country, clues, fun_facts, trivia, options, correct_answer) VALUES
-- EUROPE
('Paris', 'France', 
    ARRAY['This city is home to a famous tower that sparkles every night.', 'Known as the "City of Love" and a hub for fashion and art.'], 
    ARRAY['The Eiffel Tower was supposed to be dismantled after 20 years but was saved because it was useful for radio transmissions!', 'Paris has only one stop sign in the entire city--most intersections rely on priority-to-the-right rules.'], 
    ARRAY['This city is famous for its croissants and macarons. Bon appetit!', 'Paris was originally a Roman city called Lutetia.'],
    ARRAY['Eiffel Tower', 'Notre-Dame Cathedral', 'Louvre Museum'],
    'Eiffel Tower'
),
('London', 'United Kingdom',
    ARRAY['Home to a giant clock tower that chimes every hour.', 'Famous for its double-decker buses and black taxis.'],
    ARRAY['Big Ben is actually the name of the bell inside the clock tower, not the tower itself!', 'London has over 170 museums, more than any other city in the world.'],
    ARRAY['London''s underground is the oldest metro system in the world, dating back to 1863.', 'The Queen''s guards at Buckingham Palace are trained not to react to tourists.'],
    ARRAY['Big Ben', 'London Eye', 'Tower of London'],
    'Big Ben'
),
('Rome', 'Italy',
    ARRAY['This city has an ancient amphitheater that once hosted gladiator battles.', 'Known for its world-famous pasta and gelato.'],
    ARRAY['The Colosseum was originally called the Flavian Amphitheater.', 'There''s a secret keyhole in Rome that perfectly frames a view of St. Peter''s Basilica.'],
    ARRAY['The Vatican City, inside Rome, is the smallest country in the world.', 'Rome has more fountains than any other city, with over 1,500!'],
    ARRAY['Colosseum', 'Pantheon', 'Trevi Fountain'],
    'Colosseum'
),

-- ASIA
('Tokyo', 'Japan', 
    ARRAY['This city has the busiest pedestrian crossing in the world.', 'You can visit an entire district dedicated to anime, manga, and gaming.'], 
    ARRAY['Tokyo was originally a small fishing village called Edo before becoming the bustling capital it is today!', 'More than 14 million people live in Tokyo, making it one of the most populous cities in the world.'], 
    ARRAY['The city has over 160,000 restaurants, more than any other city in the world.', 'Tokyo''s subway system is so efficient that train delays of just a few minutes come with formal apologies.'],
    ARRAY['Shibuya Crossing', 'Tokyo Tower', 'Meiji Shrine'],
    'Shibuya Crossing'
),
('Seoul', 'South Korea',
    ARRAY['This city is home to the world''s most technologically advanced subway system.', 'Famous for K-pop, kimchi, and K-dramas.'],
    ARRAY['Seoul''s Namdaemun Market has been around since 1414!', 'There are more than 13,000 convenience stores in Seoul alone.'],
    ARRAY['South Korea has a "love lock" tradition at N Seoul Tower.', 'Seoul''s subway stations have book rental machines for passengers.'],
    ARRAY['Gyeongbokgung Palace', 'N Seoul Tower', 'Bukchon Hanok Village'],
    'Gyeongbokgung Palace'
),

-- AMERICAS
('New York', 'USA', 
    ARRAY['Home to a green statue gifted by France in the 1800s.', 'Nicknamed "The Big Apple" and known for its Broadway theaters.'], 
    ARRAY['The Statue of Liberty was originally a copper color before oxidizing to its iconic green patina.', 'Times Square was once called Longacre Square before being renamed in 1904.'], 
    ARRAY['New York City has 468 subway stations, making it one of the most complex transit systems in the world.', 'The Empire State Building has its own zip code: 10118.'],
    ARRAY['Statue of Liberty', 'Central Park', 'Empire State Building'],
    'Statue of Liberty'
),
('Rio de Janeiro', 'Brazil',
    ARRAY['This city has a massive statue of Jesus overlooking it from a mountain.', 'Known for its carnival celebrations and samba music.'],
    ARRAY['The Christ the Redeemer statue was built in France before being assembled in Brazil.', 'Rio''s Copacabana beach gets its name from a Bolivian Virgin.'],
    ARRAY['The city''s Maracanã stadium once held a record attendance of 199,854 for a football match.', 'Rio''s Sugarloaf Mountain has a cable car that offers panoramic city views.'],
    ARRAY['Christ the Redeemer', 'Sugarloaf Mountain', 'Maracanã Stadium'],
    'Christ the Redeemer'
),

-- AFRICA
('Cairo', 'Egypt',
    ARRAY['This city has the last standing Wonder of the Ancient World.', 'It is home to a river that runs through 11 countries.'],
    ARRAY['The Great Pyramid of Giza was the tallest man-made structure for 3,800 years.', 'Cairo is known as "The City of a Thousand Minarets" due to its many mosques.'],
    ARRAY['The Sphinx originally had a nose, but it was destroyed in history.', 'The Nile River is the longest in the world, stretching over 6,600 km.'],
    ARRAY['Great Pyramid of Giza', 'Sphinx', 'Cairo Museum'],
    'Great Pyramid of Giza'
),

-- OCEANIA
('Sydney', 'Australia',
    ARRAY['This city has a white sail-shaped building famous for its performances.', 'It is home to one of the world''s most beautiful harbors.'],
    ARRAY['The Sydney Opera House took 14 years to complete.', 'Sydney''s Bondi Beach has some of the most dangerous riptides in the world.'],
    ARRAY['Sydney was founded as a British penal colony in 1788.', 'The Sydney Harbour Bridge is nicknamed "The Coathanger" because of its shape.'],
    ARRAY['Sydney Opera House', 'Sydney Harbour Bridge', 'Bondi Beach'],
    'Sydney Opera House'
),

-- MIDDLE EAST
('Dubai', 'UAE',
    ARRAY['This city has the tallest building in the world.', 'Known for its man-made islands shaped like a palm tree.'],
    ARRAY['Burj Khalifa is so tall that you can watch the sunset twice on the same day--from different floors!', 'Dubai has a police force that drives luxury sports cars.'],
    ARRAY['The city has an indoor ski resort despite being in the desert.', 'Dubai has a gold vending machine where you can buy gold bars!'],
    ARRAY['Burj Khalifa', 'Palm Jumeirah', 'Dubai Mall'],
    'Burj Khalifa'
),
('Berlin', 'Germany',
    ARRAY['Known for its historical landmarks and vibrant arts scene.', 'Divided during the Cold War.'],
    ARRAY['The Berlin Wall fell in 1989.', 'Berlin has more bridges than Venice.'],
    ARRAY['The Brandenburg Gate is a symbol of German reunification.', 'Currywurst is a popular street food.'],
    ARRAY['Brandenburg Gate', 'Berlin Wall Memorial', 'Reichstag Building'],
    'Brandenburg Gate'
),
('Vienna', 'Austria',
    ARRAY['Known for its classical music and imperial palaces.', 'Home to the Habsburg dynasty.'],
    ARRAY['Vienna is known as the "City of Music."', 'The Schönbrunn Palace was the summer residence of the Habsburgs.'],
    ARRAY['Sacher torte is a famous Viennese dessert.', 'Vienna has a rich coffeehouse culture.'],
    ARRAY['Schönbrunn Palace', 'St. Stephen''s Cathedral', 'Belvedere Palace'],
    'Schönbrunn Palace'
),
('Prague', 'Czech Republic',
    ARRAY['Known for its medieval architecture and Charles Bridge.', 'Home to Prague Castle.'],
    ARRAY['Prague Castle is one of the largest ancient castles in the world.', 'The Astronomical Clock is a popular tourist attraction.'],
    ARRAY['Czech beer is world-renowned.', 'The city has a rich history of art and literature.'],
    ARRAY['Prague Castle', 'Charles Bridge', 'Old Town Square'],
    'Prague Castle'
),
('Budapest', 'Hungary',
    ARRAY['Known for its thermal baths and Danube River views.', 'Divided by the Danube into Buda and Pest.'],
    ARRAY['Budapest has numerous thermal baths.', 'The Hungarian Parliament Building is a stunning example of Gothic Revival architecture.'],
    ARRAY['Goulash is a traditional Hungarian dish.', 'The city has a vibrant nightlife.'],
    ARRAY['Hungarian Parliament Building', 'Széchenyi Thermal Bath', 'Chain Bridge'],
    'Hungarian Parliament Building'
),
('Lisbon', 'Portugal',
    ARRAY['Known for its historic neighborhoods and trams.', 'Home to the Belém Tower.'],
    ARRAY['Lisbon is one of the oldest cities in Western Europe.', 'Pastel de nata is a famous Portuguese pastry.'],
    ARRAY['The city has seven hills.', 'Fado music is a traditional Portuguese genre.'],
    ARRAY['Belém Tower', 'Jerónimos Monastery', 'São Jorge Castle'],
    'Belém Tower'
),
('Copenhagen', 'Denmark',
    ARRAY['Known for its colorful harbor and Little Mermaid statue.', 'Home to Tivoli Gardens.'],
    ARRAY['Copenhagen is a bicycle-friendly city.', 'Nyhavn is a popular harbor district.'],
    ARRAY['Danish design is world-renowned.', 'Smørrebrød is a traditional Danish open-faced sandwich.'],
    ARRAY['The Little Mermaid', 'Tivoli Gardens', 'Nyhavn'],
    'The Little Mermaid'
),
('Stockholm', 'Sweden',
    ARRAY['Known for its archipelago and Nobel Prize ceremonies.', 'Built on 14 islands.'],
    ARRAY['Stockholm is known as the "Venice of the North."', 'The Vasa Museum houses a 17th-century warship.'],
    ARRAY['Swedish meatballs are a popular dish.', 'The city has a rich history of design and innovation.'],
    ARRAY['Vasa Museum', 'Gamla Stan', 'Royal Palace'],
    'Vasa Museum'
),
('Helsinki', 'Finland',
    ARRAY['Known for its design district and saunas.', 'Home to Suomenlinna sea fortress.'],
    ARRAY['Helsinki is known as the "Daughter of the Baltic."', 'Finnish saunas are a cultural tradition.'],
    ARRAY['Reindeer meat is a traditional Finnish food.', 'The city has a vibrant arts scene.'],
    ARRAY['Suomenlinna', 'Helsinki Cathedral', 'Market Square'],
    'Suomenlinna'
),
('Dublin', 'Ireland',
    ARRAY['Known for its lively pubs and Guinness brewery.', 'Home to Trinity College.'],
    ARRAY['Dublin is known for its friendly atmosphere.', 'The Book of Kells is housed in Trinity College.'],
    ARRAY['Irish stew is a traditional dish.', 'The city has a rich literary history.'],
    ARRAY['Trinity College', 'Guinness Storehouse', 'St. Patrick''s Cathedral'],
    'Trinity College'
),
('Edinburgh', 'Scotland',
    ARRAY['Known for its medieval Old Town and Edinburgh Castle.', 'Home to the Fringe Festival.'],
    ARRAY['Edinburgh Castle sits atop an extinct volcano.', 'The Royal Mile connects Edinburgh Castle and Holyrood Palace.'],
    ARRAY['Haggis is a traditional Scottish dish.', 'The city has a rich history of literature and philosophy.'],
    ARRAY['Edinburgh Castle', 'Royal Mile', 'Arthur''s Seat'],
    'Edinburgh Castle'
),
('Brussels', 'Belgium',
    ARRAY['Known for its Grand Place and chocolate.', 'Headquarters of the European Union.'],
    ARRAY['The Grand Place is a UNESCO World Heritage Site.', 'Belgian waffles are a popular treat.'],
    ARRAY['Belgian beer is world-renowned.', 'Manneken Pis is a famous landmark.'],
    ARRAY['Grand Place', 'Atomium', 'Manneken Pis'],
    'Grand Place'
),
('Zurich', 'Switzerland',
    ARRAY['Known for its banking industry and Lake Zurich.', 'Home to the Swiss National Museum.'],
    ARRAY['Zurich is known for its high quality of life.', 'The Bahnhofstrasse is a famous shopping street.'],
    ARRAY['Swiss chocolate and cheese are world-renowned.', 'The city has a rich history of art and design.'],
    ARRAY['Lake Zurich', 'Bahnhofstrasse', 'Swiss National Museum'],
    'Lake Zurich'
),
('Oslo', 'Norway',
    ARRAY['Known for its fjords and Viking history.', 'Home to the Viking Ship Museum.'],
    ARRAY['Oslo is surrounded by forests and fjords.', 'The Vigeland Sculpture Park is a popular tourist attraction.'],
    ARRAY['Salmon is a staple of Norwegian cuisine.', 'The city has a rich history of exploration.'],
    ARRAY['Viking Ship Museum', 'Vigeland Sculpture Park', 'Oslo Opera House'],
    'Viking Ship Museum'
),
('Reykjavik', 'Iceland',
    ARRAY['Known for its geothermal pools and Northern Lights.', 'Home to Hallgrímskirkja church.'],
    ARRAY['Reykjavik is the northernmost capital city in the world.', 'The Blue Lagoon is a popular geothermal spa.'],
    ARRAY['Lamb is a staple of Icelandic cuisine.', 'The city has a vibrant arts and music scene.'],
    ARRAY['Hallgrímskirkja', 'Blue Lagoon', 'Harpa Concert Hall'],
    'Hallgrímskirkja'
),
('Athens', 'Greece',
    ARRAY['Known for its ancient ruins and the Acropolis.', 'Birthplace of democracy.'],
    ARRAY['The Parthenon is a symbol of ancient Greek civilization.', 'Greek yogurt is a popular food.'],
    ARRAY['Ouzo is a traditional Greek drink.', 'The city has a rich history of philosophy and literature.'],
    ARRAY['Acropolis', 'Parthenon', 'Ancient Agora'],
    'Acropolis'
),
('Istanbul', 'Turkey',
    ARRAY['Known for its historical landmarks and Bosphorus Strait.', 'Straddles two continents.'],
    ARRAY['The Hagia Sophia was originally a church, then a mosque, and now a museum.', 'Turkish delight is a popular sweet.'],
    ARRAY['Turkish coffee is a traditional drink.', 'The city has a rich history of empires.'],
    ARRAY['Hagia Sophia', 'Blue Mosque', 'Topkapi Palace'],
    'Hagia Sophia'
),
('Jerusalem', 'Israel',
    ARRAY['Known for its religious significance to Judaism, Christianity, and Islam.', 'Home to the Western Wall.'],
    ARRAY['The Old City of Jerusalem is a UNESCO World Heritage Site.', 'Hummus is a popular food.'],
    ARRAY['Falafel is a traditional Middle Eastern dish.', 'The city has a rich history of conflict and coexistence.'],
    ARRAY['Western Wall', 'Dome of the Rock', 'Church of the Holy Sepulchre'],
    'Western Wall'
),
('Mecca', 'Saudi Arabia',
    ARRAY['The holiest city in Islam.', 'Home to the Kaaba.'],
    ARRAY['Millions of Muslims make the Hajj pilgrimage to Mecca each year.', 'Dates are a popular food.'],
    ARRAY['Arabic coffee is a traditional drink.', 'The city has a rich history of Islamic tradition.'],
    ARRAY['Kaaba', 'Masjid al-Haram', 'Mount Arafat'],
    'Kaaba'
),('Amman', 'Jordan',
    ARRAY['Known for its ancient ruins and desert landscapes.', 'Gateway to Petra.'],
    ARRAY['Petra is a UNESCO World Heritage Site.', 'Jordanian hospitality is renowned.'],
    ARRAY['Mansaf is a traditional Jordanian dish.', 'The Dead Sea is a popular tourist destination.'],
    ARRAY['Petra', 'Wadi Rum', 'Citadel'],
    'Petra'
),
('Muscat', 'Oman',
    ARRAY['Known for its stunning mosques and coastal beauty.', 'Rich in maritime history.'],
    ARRAY['The Sultan Qaboos Grand Mosque is a major landmark.', 'Omani frankincense is highly valued.'],
    ARRAY['Halwa is a traditional Omani sweet.', 'Omani daggers (khanjars) are a symbol of culture.'],
    ARRAY['Sultan Qaboos Grand Mosque', 'Royal Opera House Muscat', 'Mutrah Corniche'],
    'Sultan Qaboos Grand Mosque'
),
('Doha', 'Qatar',
    ARRAY['Known for its modern architecture and cultural institutions.', 'Rapidly developing city.'],
    ARRAY['The Museum of Islamic Art houses a world-class collection.', 'Doha is a major hub for international travel.'],
    ARRAY['Machboos is a traditional Qatari dish.', 'Qatar is known for its pearl diving history.'],
    ARRAY['Museum of Islamic Art', 'The Pearl-Qatar', 'Souq Waqif'],
    'Museum of Islamic Art'
),
('Kuwait City', 'Kuwait',
    ARRAY['Known for its modern skyline and cultural attractions.', 'Oil-rich nation.'],
    ARRAY['The Kuwait Towers are a symbol of the city.', 'Kuwait has a rich maritime heritage.'],
    ARRAY['Machboos is also popular in Kuwait.', 'Kuwait is known for its hospitality.'],
    ARRAY['Kuwait Towers', 'Grand Mosque', 'The Avenues Mall'],
    'Kuwait Towers'
),
('Abu Dhabi', 'UAE',
    ARRAY['The capital of the UAE.', 'Known for its impressive mosques and cultural sites.'],
    ARRAY['The Sheikh Zayed Grand Mosque is a stunning landmark.', 'Abu Dhabi is a major center for business and culture.'],
    ARRAY['Harees is a traditional Emirati dish.', 'Falconry is a traditional sport.'],
    ARRAY['Sheikh Zayed Grand Mosque', 'Louvre Abu Dhabi', 'Emirates Palace'],
    'Sheikh Zayed Grand Mosque'
),('Kathmandu', 'Nepal',
    ARRAY['Known for its ancient temples and Himalayan views.', 'Gateway to the Himalayas.'],
    ARRAY['The Pashupatinath Temple is a major Hindu pilgrimage site.', 'Mount Everest is visible from Kathmandu on clear days.'],
    ARRAY['Momos are a popular Nepalese snack.', 'Thangka paintings are a traditional art form.'],
    ARRAY['Pashupatinath Temple', 'Swayambhunath (Monkey Temple)', 'Boudhanath Stupa'],
    'Pashupatinath Temple'
),
('Hanoi', 'Vietnam',
    ARRAY['Known for its Old Quarter and French colonial architecture.', 'Capital of Vietnam.'],
    ARRAY['Hoan Kiem Lake is a central landmark.', 'Water puppetry is a traditional art form.'],
    ARRAY['Pho is a famous Vietnamese noodle soup.', 'Vietnamese coffee is strong and flavorful.'],
    ARRAY['Hoan Kiem Lake', 'Old Quarter', 'Ho Chi Minh Mausoleum'],
    'Hoan Kiem Lake'
),
('Medellín', 'Colombia',
    ARRAY['Known for its innovative urban development and vibrant culture.', 'City of Eternal Spring.'],
    ARRAY['The Medellín Metro Cable offers stunning views of the city.', 'Fernando Botero''s sculptures are a major attraction.'],
    ARRAY['Bandeja Paisa is a traditional Colombian dish.', 'Medellín is famous for its flower festival.'],
    ARRAY['Fernando Botero''s Sculptures', 'Medellín Metro Cable', 'Plaza Botero'],
    'Fernando Botero''s Sculptures'
),
('Quebec City', 'Canada',
    ARRAY['Known for its historic Old Town and French-Canadian culture.', 'Only walled city north of Mexico.'],
    ARRAY['The Château Frontenac is a prominent landmark.', 'Quebec City is a UNESCO World Heritage Site.'],
    ARRAY['Poutine is a famous Canadian dish.', 'Maple syrup is a staple of Quebec cuisine.'],
    ARRAY['Château Frontenac', 'Old Quebec', 'Plains of Abraham'],
    'Château Frontenac'
),
('Auckland', 'New Zealand',
    ARRAY['Known for its harbors and Polynesian culture.', 'City of Sails.'],
    ARRAY['The Sky Tower offers panoramic views of the city.', 'Auckland is built on volcanic fields.'],
    ARRAY['Hangi is a traditional Maori cooking method.', 'New Zealand is famous for its adventure sports.'],
    ARRAY['Sky Tower', 'Auckland Harbour Bridge', 'Rangitoto Island'],
    'Sky Tower'
);
